### ISSUE TITLE
Branches & PRs

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/go-demo-app#2]
Create 3 branches:

feature-branch-1
feature-branch-2
feature-branch-3

Have one of those feature branches be failing (red) while the other are green. 

Open PRs for all of those feature-branches.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78045046-bdbefe00-7375-11ea-9d2e-b34616f83bfd.png)

![image](https://user-images.githubusercontent.com/29516565/78045063-c31c4880-7375-11ea-81d3-94a85a35249e.png)
