### ISSUE TITLE
Improve TEST DURATION HISTOGRAM to have a more "visually appealing distribution"

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/go-demo-app#3]
![image](https://user-images.githubusercontent.com/3640206/77954629-eaebad80-729c-11ea-89bd-1f8cb76a9b60.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78045108-d4fdeb80-7375-11ea-8c25-5cd41aabeeb5.png)
