### ISSUE TITLE
"demo" tests

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/go-demo-app#4]
Not sure how we're going to fix this here...

In other projects, the goal is to be able to search by "demo" to see a list of 1-5 tests that are interesting to take a look at. The problem with this project, is that since it contains the word "demo" in the project name, all of the tests automatically qualify for the "demo" filter. 

![image](https://user-images.githubusercontent.com/3640206/77954745-1ff80000-729d-11ea-9e01-aaabf100f6c6.png)

May be can add another qualifier that would work? How about `demotest`? Any other ideas? 

![image](https://user-images.githubusercontent.com/3640206/77954810-3900b100-729d-11ea-8f21-0a659d112a35.png)

**Comment by borjaburgos** [comment]
Every "demo" test should have more than one execution. Ideally there's at least one "demo" test that is flaky with passing and failing executions.

**Comment by borjaburgos** [comment]
Let's go with `demotest`.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78045165-e810bb80-7375-11ea-82f9-ee226a4bfefa.png)

**Comment by borjaburgos** [comment]
Any way to have `demotest` have more than 1 execution? May be using the matrix feature that Juan discussed. Also, I created a commit and the only test that was flaky, didn't flake :( Is the flake random?

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78138916-f5867e00-7427-11ea-866c-71938169dc43.png)
