### ISSUE TITLE
add "dummy" to the noisy tests

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/go-demo-app#5]
Add an identifier to "dummy" tests. As such, this project would have:

a very limited amount of "demo" or "demotest" tests (1-5)
a lot of "dummy" tests (~1000s)
any other test that may not be dummy tests, but still not interesting enough to be highlighted as "demo"

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78045227-fa8af500-7375-11ea-8bf0-2147c2f64b63.png)
