### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/go-demo-app#6]
README should contain instructions on how to clone this project and how to run it locally with Scope for Mac/Windows to obtain Scratchpad results.

Ideally, all integration tests are automatically configured to be ran against our "production" hamburguesía instance, such that when I run them locally I still the full traces in Scratchpad.

Add the Scope Badge to the README.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78045276-0b3b6b00-7376-11ea-972c-4de224a57fc4.png)
